#!/bin/bash

git status

GITACCOUNT_NAME=$(git config --get user.name)
GITACCOUNT_EMAIL=$(git config --get user.email)
echo "Authoring commit using \`$GITACCOUNT_NAME ($GITACCOUNT_EMAIL)\`" | gum format

trap "exit 0" INT
TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" "chore" "revert")
[ -z "$TYPE" ] && exit 0
SCOPE=$(gum input --placeholder "scope (optional)")

test -n "$SCOPE" && SCOPE="($SCOPE)"
gum confirm "breaking changes?" && PREFIX="$TYPE$SCOPE!" || PREFIX="$TYPE$SCOPE"

SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder "Summary of this change")
DESCRIPTION=$(gum write --placeholder "Details of this change (CTRL+D to finish)")

echo "$SUMMARY" | gum format
[ ! -z "$DESCRIPTION" ] && echo "$DESCRIPTION" | gum format

gum confirm "Commit changes?" && git commit -m "$SUMMARY" -m "$DESCRIPTION"

